import os
import subprocess
from pathlib import Path

import pytest

from alkaid._cli.report import _load_project


def _minimal_vivado_utilization_report() -> str:
    tracked_resources = [
        'DSPs',
        'LUT as Logic',
        'LUT as Memory',
        'CLB Registers',
        'CARRY8',
        'Register as Latch',
        'Register as Flip Flop',
        'RAMB18',
        'URAM',
        'Block RAM Tile',
    ]
    return ''.join(f'| {name} | 1 | 0 | 0 | 100 | 1 |\n' for name in tracked_resources)


def test_report_xdc_clock_period_allows_leading_comments(tmp_path):
    reports_path = tmp_path / 'output_model' / 'reports'
    reports_path.mkdir(parents=True)
    src_path = tmp_path / 'src'
    src_path.mkdir()

    (tmp_path / 'build_vivado_prj.tcl').write_text('set project_name "model"\n')
    (tmp_path / 'metadata.json').write_text('{"flavor": "verilog"}\n')
    (reports_path / 'model_post_route_util.rpt').write_text(_minimal_vivado_utilization_report())
    (src_path / 'model.xdc').write_text('\n# Generated by a downstream project.\nset clock_period 20.0\n')

    assert _load_project(tmp_path)['clock_period'] == 20.0


@pytest.mark.parametrize(
    'config',
    [['vivado', -1], ['quartus', -1], ['vitis', -1], ['vivado', 2], ['quartus', 2]],
)
def test_report(config, temp_directory):
    test_root = Path(os.environ.get('ALKAID_TEST_DIR', '/tmp/alkaid_test')) / 'test_data'
    backend, lc = config
    if backend == 'vitis':
        path = test_root / f'{backend}_example_model'
    else:
        path = test_root / f'{backend}_example_verilog_model_lc={lc}'

    subprocess.run(['alkaid', 'report', str(path)], capture_output=True, text=True, check=True)
    for ext in ['.html', '.json', '.csv', '.tsv', '.md']:
        out_path = Path(f'{temp_directory}/report{ext}')
        subprocess.run(['alkaid', 'report', str(path), '-o', out_path], capture_output=True, text=True, check=True)
        assert out_path.exists()
        out_path.unlink()
